### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by kaypee90** [kaypee90/zebrok#55]
Improve README file content to be easily understandable.

**Comment by ajaySahani7945** [comment]
Hi , my name is Ajay sahani and i would like to work on this, can you provide me some details on " Improve documentation".

**Comment by kaypee90** [comment]
> Hi , my name is Ajay sahani and i would like to work on this, can you provide me some details on " Improve documentation".

@ajaySahani7945 The idea is to improve the README file so it's easy to understand

**Comment by ajaySahani7945** [comment]
i would like to work on this. Could you assign me this issue.
